/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDrugAllergy
 */
export interface ControllersDrugAllergy {
    /**
     * 
     * @type {number}
     * @memberof ControllersDrugAllergy
     */
    doctor?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDrugAllergy
     */
    manner?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDrugAllergy
     */
    medicine?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDrugAllergy
     */
    patient?: number;
}

export function ControllersDrugAllergyFromJSON(json: any): ControllersDrugAllergy {
    return ControllersDrugAllergyFromJSONTyped(json, false);
}

export function ControllersDrugAllergyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDrugAllergy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'doctor') ? undefined : json['doctor'],
        'manner': !exists(json, 'manner') ? undefined : json['manner'],
        'medicine': !exists(json, 'medicine') ? undefined : json['medicine'],
        'patient': !exists(json, 'patient') ? undefined : json['patient'],
    };
}

export function ControllersDrugAllergyToJSON(value?: ControllersDrugAllergy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': value.doctor,
        'manner': value.manner,
        'medicine': value.medicine,
        'patient': value.patient,
    };
}


