/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntManner,
    EntMannerFromJSON,
    EntMannerFromJSONTyped,
    EntMannerToJSON,
    EntMedicine,
    EntMedicineFromJSON,
    EntMedicineFromJSONTyped,
    EntMedicineToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDrugAllergyEdges
 */
export interface EntDrugAllergyEdges {
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntDrugAllergyEdges
     */
    doctor?: EntDoctor;
    /**
     * 
     * @type {EntManner}
     * @memberof EntDrugAllergyEdges
     */
    manner?: EntManner;
    /**
     * 
     * @type {EntMedicine}
     * @memberof EntDrugAllergyEdges
     */
    medicine?: EntMedicine;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntDrugAllergyEdges
     */
    patient?: EntPatient;
}

export function EntDrugAllergyEdgesFromJSON(json: any): EntDrugAllergyEdges {
    return EntDrugAllergyEdgesFromJSONTyped(json, false);
}

export function EntDrugAllergyEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDrugAllergyEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'Doctor') ? undefined : EntDoctorFromJSON(json['Doctor']),
        'manner': !exists(json, 'Manner') ? undefined : EntMannerFromJSON(json['Manner']),
        'medicine': !exists(json, 'Medicine') ? undefined : EntMedicineFromJSON(json['Medicine']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
    };
}

export function EntDrugAllergyEdgesToJSON(value?: EntDrugAllergyEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': EntDoctorToJSON(value.doctor),
        'manner': EntMannerToJSON(value.manner),
        'medicine': EntMedicineToJSON(value.medicine),
        'patient': EntPatientToJSON(value.patient),
    };
}


