/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrugAllergy,
    EntDrugAllergyFromJSON,
    EntDrugAllergyFromJSONTyped,
    EntDrugAllergyToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDoctorEdges
 */
export interface EntDoctorEdges {
    /**
     * DoctorDrugAllergy holds the value of the Doctor_DrugAllergy edge.
     * @type {Array<EntDrugAllergy>}
     * @memberof EntDoctorEdges
     */
    doctorDrugAllergy?: Array<EntDrugAllergy>;
}

export function EntDoctorEdgesFromJSON(json: any): EntDoctorEdges {
    return EntDoctorEdgesFromJSONTyped(json, false);
}

export function EntDoctorEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDoctorEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctorDrugAllergy': !exists(json, 'doctorDrugAllergy') ? undefined : ((json['doctorDrugAllergy'] as Array<any>).map(EntDrugAllergyFromJSON)),
    };
}

export function EntDoctorEdgesToJSON(value?: EntDoctorEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctorDrugAllergy': value.doctorDrugAllergy === undefined ? undefined : ((value.doctorDrugAllergy as Array<any>).map(EntDrugAllergyToJSON)),
    };
}


