/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrugAllergy,
    EntDrugAllergyFromJSON,
    EntDrugAllergyFromJSONTyped,
    EntDrugAllergyToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMannerEdges
 */
export interface EntMannerEdges {
    /**
     * MannerDrugAllergy holds the value of the Manner_DrugAllergy edge.
     * @type {Array<EntDrugAllergy>}
     * @memberof EntMannerEdges
     */
    mannerDrugAllergy?: Array<EntDrugAllergy>;
}

export function EntMannerEdgesFromJSON(json: any): EntMannerEdges {
    return EntMannerEdgesFromJSONTyped(json, false);
}

export function EntMannerEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMannerEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mannerDrugAllergy': !exists(json, 'mannerDrugAllergy') ? undefined : ((json['mannerDrugAllergy'] as Array<any>).map(EntDrugAllergyFromJSON)),
    };
}

export function EntMannerEdgesToJSON(value?: EntMannerEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mannerDrugAllergy': value.mannerDrugAllergy === undefined ? undefined : ((value.mannerDrugAllergy as Array<any>).map(EntDrugAllergyToJSON)),
    };
}


