/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMannerEdges,
    EntMannerEdgesFromJSON,
    EntMannerEdgesFromJSONTyped,
    EntMannerEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntManner
 */
export interface EntManner {
    /**
     * MannerName holds the value of the "Manner_Name" field.
     * @type {string}
     * @memberof EntManner
     */
    mannerName?: string;
    /**
     * 
     * @type {EntMannerEdges}
     * @memberof EntManner
     */
    edges?: EntMannerEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntManner
     */
    id?: number;
}

export function EntMannerFromJSON(json: any): EntManner {
    return EntMannerFromJSONTyped(json, false);
}

export function EntMannerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntManner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mannerName': !exists(json, 'Manner_Name') ? undefined : json['Manner_Name'],
        'edges': !exists(json, 'edges') ? undefined : EntMannerEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntMannerToJSON(value?: EntManner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Manner_Name': value.mannerName,
        'edges': EntMannerEdgesToJSON(value.edges),
        'id': value.id,
    };
}


