/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrugAllergy,
    EntDrugAllergyFromJSON,
    EntDrugAllergyFromJSONTyped,
    EntDrugAllergyToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicineEdges
 */
export interface EntMedicineEdges {
    /**
     * MedicineDrugAllergy holds the value of the Medicine_DrugAllergy edge.
     * @type {Array<EntDrugAllergy>}
     * @memberof EntMedicineEdges
     */
    medicineDrugAllergy?: Array<EntDrugAllergy>;
}

export function EntMedicineEdgesFromJSON(json: any): EntMedicineEdges {
    return EntMedicineEdgesFromJSONTyped(json, false);
}

export function EntMedicineEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicineEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicineDrugAllergy': !exists(json, 'medicineDrugAllergy') ? undefined : ((json['medicineDrugAllergy'] as Array<any>).map(EntDrugAllergyFromJSON)),
    };
}

export function EntMedicineEdgesToJSON(value?: EntMedicineEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medicineDrugAllergy': value.medicineDrugAllergy === undefined ? undefined : ((value.medicineDrugAllergy as Array<any>).map(EntDrugAllergyToJSON)),
    };
}


