/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMedicineEdges,
    EntMedicineEdgesFromJSON,
    EntMedicineEdgesFromJSONTyped,
    EntMedicineEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicine
 */
export interface EntMedicine {
    /**
     * MedicineName holds the value of the "Medicine_Name" field.
     * @type {string}
     * @memberof EntMedicine
     */
    medicineName?: string;
    /**
     * 
     * @type {EntMedicineEdges}
     * @memberof EntMedicine
     */
    edges?: EntMedicineEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMedicine
     */
    id?: number;
}

export function EntMedicineFromJSON(json: any): EntMedicine {
    return EntMedicineFromJSONTyped(json, false);
}

export function EntMedicineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicineName': !exists(json, 'Medicine_Name') ? undefined : json['Medicine_Name'],
        'edges': !exists(json, 'edges') ? undefined : EntMedicineEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntMedicineToJSON(value?: EntMedicine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Medicine_Name': value.medicineName,
        'edges': EntMedicineEdgesToJSON(value.edges),
        'id': value.id,
    };
}


