/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCoveredPerson,
    EntCoveredPersonFromJSON,
    EntCoveredPersonFromJSONTyped,
    EntCoveredPersonToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * PatientCoveredPerson holds the value of the Patient_CoveredPerson edge.
     * @type {Array<EntCoveredPerson>}
     * @memberof EntPatientEdges
     */
    patientCoveredPerson?: Array<EntCoveredPerson>;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientCoveredPerson': !exists(json, 'patientCoveredPerson') ? undefined : ((json['patientCoveredPerson'] as Array<any>).map(EntCoveredPersonFromJSON)),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientCoveredPerson': value.patientCoveredPerson === undefined ? undefined : ((value.patientCoveredPerson as Array<any>).map(EntCoveredPersonToJSON)),
    };
}


