/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientEdges,
    EntPatientEdgesFromJSON,
    EntPatientEdgesFromJSONTyped,
    EntPatientEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatient
 */
export interface EntPatient {
    /**
     * PatientAge holds the value of the "Patient_Age" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientAge?: string;
    /**
     * PatientBlood holds the value of the "Patient_Blood" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientBlood?: string;
    /**
     * PatientGender holds the value of the "Patient_Gender" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientGender?: string;
    /**
     * PatientHeight holds the value of the "Patient_Height" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientHeight?: string;
    /**
     * PatientName holds the value of the "Patient_Name" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientName?: string;
    /**
     * PatientPrefix holds the value of the "Patient_Prefix" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientPrefix?: string;
    /**
     * PatientWeight holds the value of the "Patient_Weight" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientWeight?: string;
    /**
     * 
     * @type {EntPatientEdges}
     * @memberof EntPatient
     */
    edges?: EntPatientEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatient
     */
    id?: number;
}

export function EntPatientFromJSON(json: any): EntPatient {
    return EntPatientFromJSONTyped(json, false);
}

export function EntPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientAge': !exists(json, 'Patient_Age') ? undefined : json['Patient_Age'],
        'patientBlood': !exists(json, 'Patient_Blood') ? undefined : json['Patient_Blood'],
        'patientGender': !exists(json, 'Patient_Gender') ? undefined : json['Patient_Gender'],
        'patientHeight': !exists(json, 'Patient_Height') ? undefined : json['Patient_Height'],
        'patientName': !exists(json, 'Patient_Name') ? undefined : json['Patient_Name'],
        'patientPrefix': !exists(json, 'Patient_Prefix') ? undefined : json['Patient_Prefix'],
        'patientWeight': !exists(json, 'Patient_Weight') ? undefined : json['Patient_Weight'],
        'edges': !exists(json, 'edges') ? undefined : EntPatientEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPatientToJSON(value?: EntPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Patient_Age': value.patientAge,
        'Patient_Blood': value.patientBlood,
        'Patient_Gender': value.patientGender,
        'Patient_Height': value.patientHeight,
        'Patient_Name': value.patientName,
        'Patient_Prefix': value.patientPrefix,
        'Patient_Weight': value.patientWeight,
        'edges': EntPatientEdgesToJSON(value.edges),
        'id': value.id,
    };
}


